import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect } from "react";
import { ProductsContext } from "../components/context/ProductsProvider";
import { PageDrawer } from "../components/PageDrawer/PageDrawer";
import { ProductListContainer } from "../components/ProductListContainer/ProductListContainer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>e-commerce</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />

                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <PageDrawer />
                <h1>E-commerce</h1>
                <ProductListContainer />
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
